version: '3.8'

services:
  sveltekit-ui:
    image: gusdewa/live-coding:v1
    environment:
      VITE_API_URL: http://fastapi:${APP_PORT}
    ports:
      - '3000:80'
    depends_on:
      - fastapi

  fastapi:
    build: .
    hostname: fastapi
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      DB_USERNAME: postgres
      DB_PASSWORD:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DEBUG_MODE: ${DEBUG_MODE}
      APP_PORT: ${APP_PORT}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db

  db:
    restart: always
    hostname: db
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432' # to avoid conflict with local DB

volumes:
  postgres_data:
